### ISSUE TITLE
No longer auto-installs runtimes & SDKs

### ISSUE THREAD

**Issue by fcastilloec** [malept/electron-installer-flatpak#24]
**What version of `electron-installer-flatpak` are you using?** 0.11.1

**What version of `node` and `npm` are you using?** node: 12.16.3, npm: 6.14.5

**What operating system are you using?** Ubuntu 20.04

**Can you compile the [example app](https://github.com/endlessm/electron-installer-flatpak/tree/master/example) successfully?** No

**If not, paste here the output of the following commands:**
```
$ git clone https://github.com/endlessm/electron-installer-flatpak.git
$ cd electron-installer-flatpak/example
$ DEBUG='electron-installer-flatpak' npm run build
```
```
Creating package (this may take a while)
  electron-installer-flatpak Reading package metadata from dist/poopie-linux-x64/resources/app/package.json +0ms
  electron-installer-flatpak Creating package with options
  electron-installer-flatpak {
  electron-installer-flatpak   "src": "dist/poopie-linux-x64/",
  electron-installer-flatpak   "arch": "x64",
  electron-installer-flatpak   "config": "config.json",
  electron-installer-flatpak   "dest": "dist/installers/",
  electron-installer-flatpak   "icon": "resources/Icon.png",
  electron-installer-flatpak   "categories": [
  electron-installer-flatpak     "Utility"
  electron-installer-flatpak   ],
  electron-installer-flatpak   "depends": [
  electron-installer-flatpak     "git",
  electron-installer-flatpak     "gconf2",
  electron-installer-flatpak     "gconf-service",
  electron-installer-flatpak     "gvfs-bin",
  electron-installer-flatpak     "libc6",
  electron-installer-flatpak     "libcap2",
  electron-installer-flatpak     "libgtk2.0-0",
  electron-installer-flatpak     "libudev0 | libudev1",
  electron-installer-flatpak     "libgcrypt11 | libgcrypt20",
  electron-installer-flatpak     "libappindicator1",
  electron-installer-flatpak     "libnotify4",
  electron-installer-flatpak     "libnss3",
  electron-installer-flatpak     "libxtst6",
  electron-installer-flatpak     "python",
  electron-installer-flatpak     "xdg-utils"
  electron-installer-flatpak   ],
  electron-installer-flatpak   "lintianOverrides": [
  electron-installer-flatpak     "changelog-file-missing-in-native-package"
  electron-installer-flatpak   ],
  electron-installer-flatpak   "bin": "poopie",
  electron-installer-flatpak   "execArguments": [],
  electron-installer-flatpak   "description": "An example app, built with Electron.",
  electron-installer-flatpak   "genericName": "poopie",
  electron-installer-flatpak   "homepage": "",
  electron-installer-flatpak   "mimeType": [],
  electron-installer-flatpak   "name": "poopie",
  electron-installer-flatpak   "productDescription": "An example app, built with Electron.",
  electron-installer-flatpak   "productName": "poopie",
  electron-installer-flatpak   "branch": "stable",
  electron-installer-flatpak   "baseVersion": "stable",
  electron-installer-flatpak   "runtime": "org.freedesktop.Platform",
  electron-installer-flatpak   "sdk": "org.freedesktop.Sdk",
  electron-installer-flatpak   "runtimeVersion": "19.08",
  electron-installer-flatpak   "base": "org.electronjs.Electron2.BaseApp",
  electron-installer-flatpak   "id": "io.atom.electron.poopie",
  electron-installer-flatpak   "extraFlatpakBuilderArgs": [],
  electron-installer-flatpak   "finishArgs": [
  electron-installer-flatpak     "--socket=x11",
  electron-installer-flatpak     "--share=ipc",
  electron-installer-flatpak     "--device=dri",
  electron-installer-flatpak     "--socket=pulseaudio",
  electron-installer-flatpak     "--filesystem=home",
  electron-installer-flatpak     "--env=TMPDIR=/var/tmp",
  electron-installer-flatpak     "--share=network",
  electron-installer-flatpak     "--talk-name=org.freedesktop.Notifications"
  electron-installer-flatpak   ],
  electron-installer-flatpak   "modules": [
  electron-installer-flatpak     {
  electron-installer-flatpak       "name": "zypak",
  electron-installer-flatpak       "sources": [
  electron-installer-flatpak         {
  electron-installer-flatpak           "type": "git",
  electron-installer-flatpak           "url": "https://github.com/refi64/zypak",
  electron-installer-flatpak           "tag": "v2019.11beta.3"
  electron-installer-flatpak         }
  electron-installer-flatpak       ]
  electron-installer-flatpak     }
  electron-installer-flatpak   ],
  electron-installer-flatpak   "files": [],
  electron-installer-flatpak   "symlinks": []
  electron-installer-flatpak } +3ms
  electron-installer-flatpak Creating package at dist/installers/io.atom.electron.poopie_stable_x64.flatpak +112ms
(node:26972) UnhandledPromiseRejectionWarning: Error: flatpak-builder failed with status code 1
    at ChildProcess.<anonymous> (/mnt/Orpheus/workspace/electron-installer-flatpak/example/node_modules/@malept/flatpak-bundler/index.js:68:16)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:26972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by malept** [comment]
Can you add `@malept/flatpak-bundler` to `DEBUG`?

**Comment by malept** [comment]
Also, what version of `flatpak-builder` is installed?

**Comment by fcastilloec** [comment]
flatpak-builder 1.0.10

The error says that it's missing a runtime among other stuff. I thought, from what I understood from the README, a runtime wasn't needed to create a flatpak, only to run one. Also, the README says:

>Building a flatpak for an Electron app requires installing a "base" flatpak application with electron library dependencies. That base will be autoinstalled during an app build.

So, I assumed that the "base" will be taken care during build, which I assume those errors I see are related.
Here's the output with the new `DEBUG`

```
Creating package (this may take a while)
  @malept/flatpak-bundler Using manifest...
  @malept/flatpak-bundler {
  @malept/flatpak-bundler   "id": "io.atom.electron.poopie",
  @malept/flatpak-bundler   "branch": "stable",
  @malept/flatpak-bundler   "base": "io.atom.electron.BaseApp",
  @malept/flatpak-bundler   "base-version": "stable",
  @malept/flatpak-bundler   "extra-flatpak-builder-args": [
  @malept/flatpak-bundler     "--assumeyes"
  @malept/flatpak-bundler   ],
  @malept/flatpak-bundler   "runtime": "org.freedesktop.Platform",
  @malept/flatpak-bundler   "runtime-version": "1.6",
  @malept/flatpak-bundler   "sdk": "org.freedesktop.Sdk",
  @malept/flatpak-bundler   "finish-args": [
  @malept/flatpak-bundler     "--socket=x11",
  @malept/flatpak-bundler     "--share=ipc",
  @malept/flatpak-bundler     "--device=dri",
  @malept/flatpak-bundler     "--socket=pulseaudio",
  @malept/flatpak-bundler     "--filesystem=home",
  @malept/flatpak-bundler     "--env=TMPDIR=/var/tmp",
  @malept/flatpak-bundler     "--share=network",
  @malept/flatpak-bundler     "--talk-name=org.freedesktop.Notifications"
  @malept/flatpak-bundler   ],
  @malept/flatpak-bundler   "command": "poopie",
  @malept/flatpak-bundler   "files": [
  @malept/flatpak-bundler     [
  @malept/flatpak-bundler       "/tmp/electron-installer-386174fokvXP4Ajfe/io.atom.electron.poopie_undefined_x64",
  @malept/flatpak-bundler       "/"
  @malept/flatpak-bundler     ]
  @malept/flatpak-bundler   ],
  @malept/flatpak-bundler   "symlinks": [
  @malept/flatpak-bundler     [
  @malept/flatpak-bundler       "/lib/io.atom.electron.poopie/poopie",
  @malept/flatpak-bundler       "/bin/poopie"
  @malept/flatpak-bundler     ]
  @malept/flatpak-bundler   ],
  @malept/flatpak-bundler   "extra-exports": [
  @malept/flatpak-bundler     "share/pixmaps/io.atom.electron.poopie.png"
  @malept/flatpak-bundler   ],
  @malept/flatpak-bundler   "modules": []
  @malept/flatpak-bundler } +0ms
  @malept/flatpak-bundler Using options...
  @malept/flatpak-bundler {
  @malept/flatpak-bundler   "arch": "x86_64",
  @malept/flatpak-bundler   "bundle-path": "/mnt/Orpheus/workspace/electron-installer-flatpak/example/dist/installers/io.atom.electron.poopie_stable_x64.flatpak",
  @malept/flatpak-bundler   "working-dir": "/var/tmp/tmp-38617LNcVBxnfL3Qw",
  @malept/flatpak-bundler   "build-dir": "/var/tmp/tmp-38617LNcVBxnfL3Qw/build",
  @malept/flatpak-bundler   "repo-dir": "/var/tmp/tmp-38617LNcVBxnfL3Qw/repo",
  @malept/flatpak-bundler   "manifest-path": "/var/tmp/tmp-38617LNcVBxnfL3Qw/manifest.json",
  @malept/flatpak-bundler   "extra-flatpak-builder-args": [],
  @malept/flatpak-bundler   "extra-flatpak-build-bundle-args": [],
  @malept/flatpak-bundler   "extra-flatpak-build-export-args": [],
  @malept/flatpak-bundler   "clean-tmpdirs": true,
  @malept/flatpak-bundler   "auto-install-runtime": false,
  @malept/flatpak-bundler   "auto-install-sdk": false,
  @malept/flatpak-bundler   "auto-install-base": false
  @malept/flatpak-bundler } +1ms
  @malept/flatpak-bundler $ flatpak-builder --arch x86_64 --force-clean --allow-missing-runtimes --build-only /var/tmp/tmp-38617LNcVBxnfL3Qw/build /var/tmp/tmp-38617LNcVBxnfL3Qw/manifest.json +0ms
  @malept/flatpak-bundler 2> 
  @malept/flatpak-bundler (flatpak-builder:38630): flatpak-builder-WARNING **: 20:48:41.497: Unknown property extra-flatpak-builder-args for type BuilderManifest
  @malept/flatpak-bundler 
  @malept/flatpak-bundler (flatpak-builder:38630): flatpak-builder-WARNING **: 20:48:41.497: Unknown property files for type BuilderManifest
  @malept/flatpak-bundler 
  @malept/flatpak-bundler (flatpak-builder:38630): flatpak-builder-WARNING **: 20:48:41.497: Unknown property symlinks for type BuilderManifest
  @malept/flatpak-bundler 
  @malept/flatpak-bundler (flatpak-builder:38630): flatpak-builder-WARNING **: 20:48:41.497: Unknown property extra-exports for type BuilderManifest
  @malept/flatpak-bundler  +19ms
  @malept/flatpak-bundler 2> error: org.freedesktop.Sdk/x86_64/1.6 not installed
  @malept/flatpak-bundler  +66ms
  @malept/flatpak-bundler 2> error: org.freedesktop.Sdk/x86_64/1.6 not installed
  @malept/flatpak-bundler  +140ms
  @malept/flatpak-bundler 2> error: org.freedesktop.Platform/x86_64/1.6 not installed
  @malept/flatpak-bundler  +180ms
  @malept/flatpak-bundler 2> error: io.atom.electron.BaseApp/x86_64/stable not installed
  @malept/flatpak-bundler  +181ms
  @malept/flatpak-bundler 2> Failed to init: Unable to find app io.atom.electron.BaseApp version stable
  @malept/flatpak-bundler  +1ms
(node:38617) UnhandledPromiseRejectionWarning: Error: flatpak-builder failed with status code 1
    at ChildProcess.<anonymous> (/mnt/Orpheus/workspace/electron-installer-flatpak/example/node_modules/@malept/flatpak-bundler/index.js:68:16)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:38617) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38617) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fcastilloec** [comment]
Also, the example uses `electron-prebuilt` which has been deprecated a while ago and should be replaced with `electron`

**Comment by malept** [comment]
Yeah, I haven't updated the example like the other installer modules.

**Comment by malept** [comment]
At one point, flatpak-bundler *did* auto-install SDKs and runtimes, not sure what's happening now.

**Comment by malept** [comment]
> Also, the example uses `electron-prebuilt` which has been deprecated a while ago and should be replaced with `electron`.

Fixed in https://github.com/malept/electron-installer-flatpak/commit/5554ff1d33c25382b555e61205f1bd307f12a063

**Comment by fcastilloec** [comment]
Thanks, I'm going to try this module with some of my projects.
